### ISSUE TITLE
Špatné pořadí tasků v cesnet.perun_docker_server roli

### ISSUE THREAD

**Issue by drobnymichal** [CESNET/ansible-role-perun-docker-server#148]
Dobrý den,

při nasazování nové verze Perunu na MU jsme narazili na bug v ansible roli `cesnet.perun_docker_server`.

V souboru `tasks/main.yml` se nejprve volá role firewall s proměnnou `firewall_open_tcp_ports`, která je utvořena spojením jiných proměnných. Jednou z těchto proměnných je `perun_firewall_perun_net_related_rules`. Tato proměnná však není v době renderování definovaná a ansible bohužel nezahlásí žádnou chybu. Vznikne z toho tedy seznam položek, kde jeden prvek seznamu je typu None. Kvůli tomu poté spadne renderování Templatu pro iptables.

Tato proměnná je poté definována níže v kódu. Podle mě by stačilo, aby se firewall task přesunul za definování dané proměnné nebo aby se proměnná definovala v defaults jako prázdný seznam.

Kdyby bylo nutné, tak pošlu více informací.

Díky.

Michal Drobný

**Comment by martin-kuba** [comment]
> V souboru `tasks/main.yml` se nejprve volá role firewall s proměnnou `firewall_open_tcp_ports`, která je utvořena spojením jiných proměnných. Jednou z těchto proměnných je `perun_firewall_perun_net_related_rules`. Tato proměnná však není v době renderování definovaná a ansible bohužel nezahlásí žádnou chybu. Vznikne z toho tedy seznam položek, kde jeden prvek seznamu je typu None. Kvůli tomu poté spadne renderování Templatu pro iptables.

Tomu hlášení nerozumím.  Daná část `tasks/main.yml` vypadá takto:
```yaml
- name: "compute firewall rules"
  tags: firewall
  block:
    - name: "get perun_net info"
      docker_network_info:
        name: perun_net
      register: perun_net_info
    - name: "compute facts"
      set_fact:
        perun_firewall_perun_net_related_rules:
          - { port: 25, ipv4: "{{ perun_net_info.network.IPAM.Config[0].Subnet }}", comment: "accept SMTP from docker subnet" }
          - { port: 389, ipv4: "{{ perun_net_info.network.IPAM.Config[0].Subnet }}", comment: "accept non-encrypted ldap from docker subnet"}
          - { port: 5432, ipv4: "{{ perun_net_info.network.IPAM.Config[0].Subnet }}", comment: "accept postgres from docker subnet" }

- name: "set firewall rules"
  import_role:
    name: cesnet.firewall
  vars:
    firewall_do_install: false
    firewall_do_config: true
    firewall_open_tcp_ports: "{{ perun_firewall_open_tcp_ports + perun_firewall_open_ldap_ports + perun_firewall_open_postgres_ports + perun_firewall_perun_net_related_rules + site_specific_open_tcp_ports }}"
    firewall_docker_rules: "{{ perun_firewall_docker_rules }}"
```
Tedy proměnná `perun_firewall_perun_net_related_rules` je vytvořena na řádku 141 pomocí modulu `set_fact`, a vzápětí použita na řádku 152 pro součet polí. Vzhledem k tomu, že úovdní block má stejný tag `firewall` jako později volaná role `cesnet.firewall`, nedovedu si představit situaci, ve které by mohla být ta proměnná nedefinovaná.
